# Generated by Django 4.0.3 on 2022-04-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='API_KEY',
        ),
    ]
