# Generated by Django 3.2.14 on 2022-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, unique=True)),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('surl', models.URLField()),
                ('furl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MangaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='mangauser',
            constraint=models.UniqueConstraint(fields=('email',), name='email_constraint'),
        ),
    ]
