# Generated by Django 4.0.4 on 2022-06-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangauser',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
