# Generated by Django 4.0.4 on 2022-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mangauser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangauser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
